#!/bin/sh
# --- Copyright University of Sussex 1990.  All rights reserved. ---------
# File:            C.unix/com/mkboole
# Purpose:         Build saved image for lib logic
# Author:          Aaron Sloman, April 1987 (see revisions)
# Documentation:   HELP * LOGIC
# Related Files:   C.vms/com/mkboole.com


$popsys/pop11 %nort %noinit << \\\\

lib logic
false -> popgctrace;
if syssave('$poplocalbin/boole.psv') then
	logic;
	sysexit();
endif;
sysexit();

\\

rm -f $poplocalbin/boole.psv*-
echo "boole.psv made, in $poplocalbin"

# --- Revision History ---------------------------------------------------
# --- Aaron Sloman, 3 Oct 2012      Corrected typo in 'echo' command
# --- John Gibson, May 24 1991		Added %nort arg
# --- John Williams, Oct  9 1990 	%noinit instead of =noinit
# --- John Williams, Oct  4 1990 	Now uses =noinit
# --- John Williams, Jan 15 1990	Tidied up message printed at end.
