#!/bin/sh
##
## $local/com/LINK_MOTIF_POPLOG
## Last Modified for Prelink version: 10 Oct 2015

## Included in $usepop/INSTALL/LINK_MOTIF_POPLOG
## Relink poplog and then rebuild saved images with motif.
##
## Aaron Sloman (http://www.cs.bham.ac.uk/~axs/)
## 17 Jan 2005

## Previously checked whether it was OK to link pop11 with X window
## libraries.
## Now isn't called unless it is OK.

## This script links poplog with dependence on motif, using the
##      $popcom/mkstartup
## script (invoked by newpop)

echo "Assuming you have already run CHECK_LINUX_FACILITIES"

echo ""
echo "======================================================"
echo ""

echo running "./LINK_WITHOUT_NEWPOP motif"

./LINK_WITHOUT_NEWPOP motif

echo "done LINK MOTIF POPLOG"
echo "==================================================="
echo ""
